# frozen_string_literal: true

name              'htpasswd'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Provides the htpasswd resource'
source_url        'https://github.com/sous-chefs/htpasswd'
issues_url        'https://github.com/sous-chefs/htpasswd/issues'
chef_version      '>= 15.3'
version           '2.0.18'

supports 'almalinux', '>= 8.0'
supports 'amazon', '>= 2023.0'
supports 'centos_stream', '>= 9.0'
supports 'debian', '>= 12.0'
supports 'fedora'
supports 'oracle', '>= 8.0'
supports 'redhat', '>= 8.0'
supports 'rocky', '>= 8.0'
supports 'ubuntu', '>= 22.04'
